### ISSUE TITLE
"Smart Contract" Kavramının Çevirisi

### ISSUE THREAD

**Issue by AliErcanOzgokce** [solidity-docs/tr-turkish#45]
Bazı kişiler kavramı hiç çevirmemeyi, bazıları "Akıllı Sözleşmeler" şeklinde çevirmeyi bazıları da "Akıllı Kontraktlar" şeklinde çevirmemizi istiyor. Bu konudaki görüşleriniz nelerdir?

**Comment by muratartan** [comment]
"kontrat" sözcüğü bana daha teknik bir sözcük oldugundan daha hoş geliyor, üstelik dilimize de girmiş bir sözcük. Ancak farklı birçok yerde yapılan çevirilerde hep "sözleşme" diye çevrildiğini gördüm ve ekosistem tarafından da benimsendi bu sözcük, fonksiyonu işlev diye çevirmek gibi benimsenmemiş bir durum da yok. Aslında ikisi de kullanılabilir tamamen çevirmenin insiyatifine bağlı, çeviren tek kişi olsam ben kontrat derdim. Ama bizim dökümanın bütün yerlerinde aynı sözcüğü kullanmamız gerekeceği için ortak bir karar alamız gerekecek. Sanırım birçok yerde "sözleşme" diye çevirdik, o yüzden sözleşme olarak çevrilmesi yönünde oy veriyorum.

**Comment by kuzdogan** [comment]
Sözleşme bence doğrudan karşılıyor anlamı bu yüzden burada Türkçe kelime daha uygun olur diye düşünüyorum.

**Comment by AliErcanOzgokce** [comment]
Tamamdır "Akıllı Sözleşme" olarak kavram dizinine ekliyorum.
