### ISSUE TITLE
"Statement" Kavramının Çevirisi

### ISSUE THREAD

**Issue by AliErcanOzgokce** [solidity-docs/tr-turkish#46]
Statement için en uygun karşılık bence "ifade". ama biraz düşündüğümde "komut" da uygun gibi, çünkü mesela Rust'ta şöyle bir kural var, eğer yazdıgın satır bir statement ise sonuna noktalı virgül koyma kuralı var, değilse koyulmaz. Mesela bir değişken tanımladıgımızda noktalı virgül koyulur şarttır çünkü aslında bir komut vermiş oluyoruz "git şu adda bir değişken tanımla ve değerini şuna eşitle" şeklinde. Ama mesela bir function dan bir şey return ettiğimizde noktalı virgül koydurmuyor, halbuki o da bir komut "function dan geriye bunu dönder" diyoruz. Bunlara göre düşünürsek neticede "ifade" daha uygun gibi gözüküyor, yine de yoruma açık.

_Originally posted by @muratartan in https://github.com/solidity-docs/tr-turkish/pull/42#pullrequestreview-1048990713_

**Comment by kuzdogan** [comment]
"komut" daha "command" gibi bi eyleme yakın duruyor. "ifade" bence de uygun.

**Comment by AliErcanOzgokce** [comment]
Tamamdır, "İfade" kavramını kavram dizinine ekliyorum.
