### ISSUE TITLE
"Breakpoint" Kavramının Çevirisi

### ISSUE THREAD

**Issue by AliErcanOzgokce** [solidity-docs/tr-turkish#47]
Çevrilmeden kalınması isteniyor. Alternatif çeviri örneği olarak "Kesme/Kesim Noktası" var

**Comment by kuzdogan** [comment]
Breakpoint daha kolay gibi gelse de bence "kesme noktası" kullanımı oturtulabilir. Düşününce doğrudan çeviri ile anlamı karşılıyor. Buralarda da "kesme noktası" denmiş 
https://statik.tse.org.tr/upload/tr/dosya/icerikyonetimi/552/19012016170409-4.pdfv
http://cayfer.bilkent.edu.tr/~cayfer/bilisim-sozlugu/tbd-ing-trk-sozluk.htm

**Comment by AliErcanOzgokce** [comment]
Katılıyorum, kavram dizinine ekledim
