### ISSUE TITLE
"Jump Type" Kavramının Çevirisi

### ISSUE THREAD

**Issue by AliErcanOzgokce** [solidity-docs/tr-turkish#48]
"jump type" ı araştırdım ama pek bir şey bulamadım, sanırım kontrat ataklarıyla ilgili bir konu, belki Kaan hoca bir yorum ve öneri getirir, bence ya jump ı parantez içinde yazalım ya da jump yazıp Türkçe sini parantez içine alalım.

_Originally posted by @muratartan in https://github.com/solidity-docs/tr-turkish/pull/42#discussion_r928557784_

**Comment by kuzdogan** [comment]
Jump type'tan kasıt jump opcode'un hangi türü olduğu, aşağıda anlatılmış:

> The fields s, l and f are as above. j can be either i, o or - signifying whether a jump instruction goes into a function, returns from a function or is a regular jump as part of e.g. a loop.

"Sıçrama komutu türü" denebilir burada öyle denmiş https://statik.tse.org.tr/upload/tr/dosya/icerikyonetimi/552/19012016170409-4.pdf
