### ISSUE TITLE
"Type" Kavramının Çevirisi

### ISSUE THREAD

**Issue by AliErcanOzgokce** [solidity-docs/tr-turkish#49]
Ek olarak, 'Type' kelimesini tür ve tip olarak farklı farklı kullanmışsınız tip çok doğru bir kullanım olmuyor bu bağlamda tekrar gözden geçirebilirsiniz.

_Originally posted by @sevvalmutlu in https://github.com/solidity-docs/tr-turkish/pull/30#pullrequestreview-1050952505_

**Comment by muratartan** [comment]
"Tip" sözcüğü Türkçe değil, dilimize Fransızca "type" sözcüğünden evrilerek girmiş, İngilizceye de Fransızcadan girmiş. Yani aslında "tip" derken biz halihazırda orijinali olan "type" demiş oluyoruz. "Tip" in öz Türkçesi de "tür".
Hangisini kullanacağımız pek fark etmiyor, ben orjinaline daha yakın olan tip sözcüğünü tercih ediyorum.

**Comment by kuzdogan** [comment]
"Kontrat tipi" "fonksiyon tipi" şeklinde kullanırken bana da daha uygun gelse de sadece "Type" kullanımda "Tip" çok kulağa hoş gelmedi bana. Burada genelde tek başına kullanılıyor örneğin https://github.com/solidity-docs/tr-turkish/pull/24/files

O yüzden Tür diyeceğim

**Comment by AliErcanOzgokce** [comment]
Bende "Tür" çevirisini tercih ediyorum. Ama ek olarak kavram dizinine "Tür/Tip" şeklinde eklemek pek sorun olmaz diye düşünüyorum.
