### ISSUE TITLE
Glossary (kavramlar dizini) 

### ISSUE THREAD

**Issue by kuzdogan** [solidity-docs/tr-turkish#5]
Çeviri süresince çok sayıda kelimenin Türkçe karşılığını bulmak gerekecek, veya var olan karşılıkları da çok kullanılmadığı için anlaşılmayabiliyor. 

Bunun için çeviri rehberinde [bahsedildiği gibi](https://github.com/solidity-docs/translation-guide/blob/main/maintainer-guide.md#glossary) bi "Glossary" (kavramlar dizini) hazırlamak iyi olabilir. README'ye koyabiliriz

**Comment by AliErcanOzgokce** [comment]
Haklısın, bunu tek seferde yapmak yerine sürekli güncellemek daha mantıklı olabilir.

**Comment by AliErcanOzgokce** [comment]
Şimdilik bir tane oluşturalım. Karar kıldığımız kelimeler oldukça dizini güncelleriz.
