### ISSUE TITLE
"Currently Silently Wraps" Kavramının Çevirisi

### ISSUE THREAD

**Issue by AliErcanOzgokce** [solidity-docs/tr-turkish#50]
"currently silently wraps" derken ne demek istiyor anlayamadım, biz anlamıyorsak başkaları da anlamayabilir, buna bir açıklık getirmek gerek. Belki Kaan hocamız @kuzdogan  bir fikir verebilir.

_Originally posted by @muratartan in https://github.com/solidity-docs/tr-turkish/pull/41#pullrequestreview-1049032215_

**Comment by kuzdogan** [comment]
Oldukça zormuş bu. "Wrap"ten anladığım burada bir sayı olması gerekenden uzunsa bölmek. Örneğin `1111 1111 1111 0001 1010` sayısının 16 bit olması gerekiyorsa `1111 1111 1111 0001` ve `1010` şeklinde bölünmesi. Wrap, web geliştirmede de satır atlamak için kullanılıyor, sanırım bu bağlamda kullanılmış. 

Uyarı vermeden böler diyip geçebiliriz ben de %100 emin değilim.

**Comment by AliErcanOzgokce** [comment]
__Üst limit değerinin üzerinde veya alt limit değerinin altında değer atanırsa, solidity şuan kendi atadığı değeri döndürür. Şuan da doğru olmayan rakamları limit dahilinde tutar. Gelecek sürümde hata verir.__ 

__Max small int = 255 ise, sen 256 gönderirsen 255'e atıyor.__

@cdemircioglu böyle bir açıklamada bulundu. https://hackernoon.com/hack-solidity-integer-overflow-and-underflow

**Comment by cdemircioglu** [comment]
255 degilde 0 olacak. Manuel dort haneli bir sayac gibi, 9999'a geldiginde
ve 1 eklendiginde, sayac 0000'a donuyor.

**Comment by kuzdogan** [comment]
Anlaşılan pek de iyi ifade edilememiş https://github.com/ethereum/solidity/pull/13381. İkimizin dediği de değilmiş burada bahsedilen. 

Şimdilik "sessizce doğru formata getirilir" diyelim. Bi sonraki sürümde yeni dokümantasyonu çeviririz
