### ISSUE TITLE
"Inheritance" Kavramının Çevirisi

### ISSUE THREAD

**Issue by AliErcanOzgokce** [solidity-docs/tr-turkish#51]
inheritance = kalıt almak olarak geçmiş bence daha uygun
http://cayfer.bilkent.edu.tr/~cayfer/bilisim-sozlugu/tbd-ing-trk-sozluk.htm
https://statik.tse.org.tr/upload/tr/dosya/icerikyonetimi/552/19012016170409-4.pdf

_Originally posted by @kuzdogan in https://github.com/solidity-docs/tr-turkish/pull/22#discussion_r916200026_

**Comment by muratartan** [comment]
eskiden Türkçe bir Java kitabına çalışırken orada"inheritance" başlığı "kalıtım" diye çevrilmişti. bence "kalıtım" çok yerinde bir çeviri.

**Comment by kuzdogan** [comment]
Fiil hali "inherit" = kalıt almak
İsim hali "inheritance" = kalıtım

uygun diye düşünüyorum.

**Comment by AliErcanOzgokce** [comment]
Tamamdır, "Kalıtım" kavramını kavram dizinine ekliyorum.
