### ISSUE TITLE
"Optimizer" Kavramının Çevirisi

### ISSUE THREAD

**Issue by AliErcanOzgokce** [solidity-docs/tr-turkish#53]
Optimize Edici/ Optimizer / İyileştirici

**Comment by muratartan** [comment]
optimize etmek "en iyileştirmek" anlamına geldiğinden sadece "iyileştirmek" dersek kavramın gerçek karşılıgını vermemiş oluruz, o yüzden bence "optimize edici" denilebilir. 
Gerçekten de solidity de optimizer lar bir şeyi en iyileştirmeye çalışan bir olgu mu onu tam bilemiyorum, bazen sözcük anlamıyla alakalı olmayabiliyor çünkü, böyle bir durum varsa yaptıgı işleve göre bir Türkçe karşılık bulabiliriz.

**Comment by kuzdogan** [comment]
optimize edici +1

**Comment by AliErcanOzgokce** [comment]
Tamamdır, "Optimize Edici" olarak kavram dizinine ekliyorum.
